const Map<String, List<Map<String, String>>> categorizedSoundList = {
  'Sound Effects🔊': [
    {
      'label': 'Censor Bleep Mid',
      'id': 'censor_bleep_mid',
      'icon': '🔇',
      'audio': 'sfx/sound_effects/Censor_Bleep-1kHz01-1(Mid).mp3',
    },
    {
      'label': 'Censor Bleep Synth',
      'id': 'censor_bleep_synth_short',
      'icon': '🔇',
      'audio': 'sfx/sound_effects/Censor_Bleep-Synth01-1(Short).mp3',
    },
    {
      'label': 'Countdown 1',
      'id': 'countdown1',
      'icon': '🕰️',
      'audio': 'sfx/sound_effects/Countdown04-1.mp3',
    },
    {
      'label': 'Countdown 2',
      'id': 'countdown2',
      'icon': '🕰️',
      'audio': 'sfx/sound_effects/Countdown05-1.mp3',
    },
    {
      'label': 'Countdown 3',
      'id': 'countdown3',
      'icon': '🕰️',
      'audio': 'sfx/sound_effects/Countdown06-1.mp3',
    },
    {
      'label': 'Cyber Sound 1',
      'id': 'cyber_sound1',
      'icon': '🤖',
      'audio': 'sfx/sound_effects/Cyber07-1.mp3',
    },
    {
      'label': 'Cyber Sound 2',
      'id': 'cyber_sound2',
      'icon': '🤖',
      'audio': 'sfx/sound_effects/Cyber11-1.mp3',
    },
    {
      'label': 'Cyber Sound 3',
      'id': 'cyber_sound3',
      'icon': '🤖',
      'audio': 'sfx/sound_effects/Cyber12-1.mp3',
    },
    {
      'label': 'Horagai',
      'id': 'horagai',
      'icon': '📣',
      'audio': 'sfx/sound_effects/Horagai01-1.mp3',
    },
    {
      'label': 'Quiz Buzzer',
      'id': 'quiz_buzzer',
      'icon': '📣',
      'audio': 'sfx/sound_effects/Quiz-Buzzer02-1.mp3',
    },
    {
      'label': 'Quiz Correct Answer',
      'id': 'quiz_correct_answer',
      'icon': '🎉',
      'audio': 'sfx/sound_effects/Quiz-Correct_Answer01-1.mp3',
    },
    {
      'label': 'Quiz Question 1',
      'id': 'quiz_question1',
      'icon': '📝',
      'audio': 'sfx/sound_effects/Quiz-Question02-1.mp3',
    },
    {
      'label': 'Quiz Question 2',
      'id': 'quiz_question2',
      'icon': '📝',
      'audio': 'sfx/sound_effects/Quiz-Question03-1.mp3',
    },
    {
      'label': 'Quiz Results 1',
      'id': 'quiz_results1',
      'icon': '📊',
      'audio': 'sfx/sound_effects/Quiz-Results01-1.mp3',
    },
    {
      'label': 'Quiz Results 2',
      'id': 'quiz_results2',
      'icon': '📊',
      'audio': 'sfx/sound_effects/Quiz-Results02-1.mp3',
    },
    {
      'label': 'Quiz Wrong Buzzer',
      'id': 'quiz_wrong_buzzer',
      'icon': '🚫',
      'audio': 'sfx/sound_effects/Quiz-Wrong_Buzzer02-3.mp3',
    },
    {
      'label': 'Warning Siren 1',
      'id': 'warning_siren_slow_short',
      'icon': '⚠️',
      'audio': 'sfx/sound_effects/Warning-Siren02-01(Slow-Short).mp3',
    },
    {
      'label': 'Warning Siren 2',
      'id': 'warning_siren_low_mid',
      'icon': '⚠️',
      'audio': 'sfx/sound_effects/Warning-Siren04-01(Low-Mid).mp3',
    },
    {
      'label': 'Warning Siren 3',
      'id': 'warning_siren_fast_mid',
      'icon': '⚠️',
      'audio': 'sfx/sound_effects/Warning-Siren05-01(Fast-Mid).mp3',
    },
  ],
  'Human 😋': [
    {
      'label': 'Clap',
      'id': 'clap_alone1',
      'icon': '👏',
      'audio': 'sfx/human/clap_alone1.mp3',
    },
    {
      'label': 'Finger Snap',
      'id': 'snap1',
      'icon': '👌',
      'audio': 'sfx/human/snap1.mp3',
    },
    {
      'label': 'Brushing teeth',
      'id': 'brush_teeth1',
      'icon': '🦷',
      'audio': 'sfx/human/brush_teeth1.mp3',
    },
    {
      'label': 'Fart',
      'id': 'fart1',
      'icon': '😳',
      'audio': 'sfx/human/fart1.mp3',
    },
    {
      'label': 'Heartbeat',
      'id': 'heartbeats',
      'icon': '❤️',
      'audio': 'sfx/human/heartbeats.mp3',
    },
    {
      'label': 'Hungry',
      'id': 'hungry',
      'icon': '😋',
      'audio': 'sfx/human/hungry.mp3',
    },
    {
      'label': 'Running',
      'id': 'start_running',
      'icon': '🏃‍♂️',
      'audio': 'sfx/human/start_running.mp3',
    },
    {
      'label': 'Walk',
      'id': 'walk_on_leaves1',
      'icon': '🚶‍♂️',
      'audio': 'sfx/human/walk_on_leaves1.mp3',
    },
    {
      'label': 'Whistle 1',
      'id': 'whistle2',
      'icon': '🎶',
      'audio': 'sfx/human/whistle2.mp3',
    },
    {
      'label': 'Whistle 2',
      'id': 'whistle3',
      'icon': '🎶',
      'audio': 'sfx/human/whistle3.mp3',
    },
    {
      'label': 'Baby Laughing 1',
      'id': 'baby_laugh_1',
      'icon': '👶', // 赤ちゃんのアイコンを使用
      'audio': 'sfx/human/VSQSE_1168_baby_14_laughing.mp3',
    },
    {
      'label': 'Baby Laughing 2',
      'id': 'baby_laugh_2',
      'icon': '👶', // 赤ちゃんのアイコンを使用
      'audio': 'sfx/human/VSQSE_1171_baby_17_laughing.mp3',
    },
    {
      'label': 'Baby Crying 1',
      'id': 'baby_cry_1',
      'icon': '👶', // 赤ちゃんのアイコンを使用
      'audio': 'sfx/human/VSQSE_1158_baby_04_crying.mp3',
    },
    {
      'label': 'Baby Crying 2',
      'id': 'baby_cry_2',
      'icon': '👶', // 赤ちゃんのアイコンを使用
      'audio': 'sfx/human/VSQSE_1159_baby_05_crying.mp3',
    },
    {
      'label': 'Newspaper',
      'id': 'newspaper',
      'icon': '📰', // 新聞のアイコンを使用
      'audio': 'sfx/human/VSQSE_1097_newspaper_01.mp3',
    },
  ],
  'Animal 🐈': [
    {
      'label': 'Cat 1',
      'id': 'cat1',
      'icon': '🐈',
      'audio': 'sfx/animals/cat1a.mp3',
    },
    {
      'label': 'Cat 2',
      'id': 'cat2',
      'icon': '🐈',
      'audio': 'sfx/animals/cat2a.mp3',
    },
    {
      'label': 'Cat 3',
      'id': 'cat_sweet_voice',
      'icon': '🐈',
      'audio': 'sfx/animals/cat_sweet_voice1.mp3',
    },
    {
      'label': 'Cow',
      'id': 'cow',
      'icon': '🐮',
      'audio': 'sfx/animals/cow1.mp3',
    },
    {
      'label': 'Dog 1',
      'id': 'dog1',
      'icon': '🐕',
      'audio': 'sfx/animals/dog1a.mp3',
    },
    {
      'label': 'Dog 2',
      'id': 'dog2',
      'icon': '🐕',
      'audio': 'sfx/animals/dog2a.mp3',
    },
    {
      'label': 'Crow 1',
      'id': 'crow1',
      'icon': '🐦',
      'audio': 'sfx/animals/crow1.mp3',
    },
    {
      'label': 'Crow 2',
      'id': 'crow3',
      'icon': '🐦',
      'audio': 'sfx/animals/crow3.mp3',
    },
    {
      'label': 'Chick',
      'id': 'like_chick',
      'icon': '🐓',
      'audio': 'sfx/animals/like_chick.mp3',
    },
    {
      'label': 'Howling',
      'id': 'howling',
      'icon': '🐺',
      'audio': 'sfx/animals/howling.mp3',
    },
    {
      'label': 'Owl',
      'id': 'owl',
      'icon': '🦉',
      'audio': 'sfx/animals/owl.mp3',
    },
    {
      'label': 'Panda',
      'id': 'panda',
      'icon': '🐼',
      'audio': 'sfx/animals/panda.mp3',
    },
    {
      'label': 'Sparrow',
      'id': 'sparrows',
      'icon': '🐦',
      'audio': 'sfx/animals/sparrows.mp3',
    },
    {
      'label': 'Bush Warbler',
      'id': 'warbler3',
      'icon': '🐦',
      'audio': 'sfx/animals/warbler3.mp3',
    },
    {
      'label': 'Tiger',
      'id': 'tiger01',
      'icon': '🐯',
      'audio': 'sfx/animals/tiger01.mp3',
    },
    {
      'label': 'Horse',
      'id': 'horse01',
      'icon': '🐴',
      'audio': 'sfx/animals/horse01.mp3',
    },
  ],
  'Combat⚔️': [
    {
      'label': 'Cannon Fire',
      'id': 'cannon_fire',
      'icon': '🔫',
      'audio': 'sfx/combat/Cannon01-1.mp3',
    },
    {
      'label': 'Cutting Sound 1',
      'id': 'cutting_sound1',
      'icon': '🗡️',
      'audio': 'sfx/combat/Cut02-1.mp3',
    },
    {
      'label': 'Cutting Sound 2',
      'id': 'cutting_sound2',
      'icon': '🗡️',
      'audio': 'sfx/combat/Cut03-1.mp3',
    },
    {
      'label': 'Cutting Sound 3',
      'id': 'cutting_sound3',
      'icon': '🗡️',
      'audio': 'sfx/combat/Cut04-1.mp3',
    },
    {
      'label': 'Electric Shock 1',
      'id': 'electric_shock_long',
      'icon': '⚡️',
      'audio': 'sfx/combat/Electric_Shock01-1(Long).mp3',
    },
    {
      'label': 'Electric Shock 2',
      'id': 'electric_shock_short1',
      'icon': '⚡️',
      'audio': 'sfx/combat/Electric_Shock03-1(Timbre1-Short).mp3',
    },
    {
      'label': 'Electric Shock 3',
      'id': 'electric_shock_long2',
      'icon': '⚡️',
      'audio': 'sfx/combat/Electric_Shock05-1(Long).mp3',
    },
    {
      'label': 'Electric Shock 4',
      'id': 'electric_shock_short2',
      'icon': '⚡️',
      'audio': 'sfx/combat/Electric_Shock06-1(Short).mp3',
    },
    {
      'label': 'Fracture Sound 1',
      'id': 'fracture_sound1',
      'icon': '💥',
      'audio': 'sfx/combat/Fracture02-1(Dry).mp3',
    },
    {
      'label': 'Fracture Sound 2',
      'id': 'fracture_sound2',
      'icon': '💥',
      'audio': 'sfx/combat/Fracture03-1(Dry).mp3',
    },
    {
      'label': 'Gunshot',
      'id': 'gunshot',
      'icon': '🔫',
      'audio': 'sfx/combat/Gunshot01-1.mp3',
    },
    {
      'label': 'Hit Sound 1',
      'id': 'hit_sound1',
      'icon': '🥊',
      'audio': 'sfx/combat/Hit06-1.mp3',
    },
    {
      'label': 'Hit Sound 2',
      'id': 'hit_sound2',
      'icon': '🥊',
      'audio': 'sfx/combat/Hit07-1.mp3',
    },
    {
      'label': 'Hit Sound 3',
      'id': 'hit_sound3',
      'icon': '🥊',
      'audio': 'sfx/combat/Hit09-1.mp3',
    },
    {
      'label': 'Retro Anime Explosion',
      'id': 'retro_anime_explosion',
      'icon': '🎮',
      'audio': 'sfx/combat/Retro_Anime-Explosion05-1(High-Short).mp3',
    },
    {
      'label': 'Retro Anime Gun 1',
      'id': 'retro_anime_gun_long',
      'icon': '🎮',
      'audio': 'sfx/combat/Retro_Anime-Gun03-1(Long).mp3',
    },
    {
      'label': 'Retro Anime Gun 2',
      'id': 'retro_anime_gun',
      'icon': '🎮',
      'audio': 'sfx/combat/Retro_Anime-Gun05-1.mp3',
    },
    {
      'label': 'Retro Anime Gun 3',
      'id': 'retro_anime_gun_long2',
      'icon': '🎮',
      'audio': 'sfx/combat/Retro_Anime-Gun10-1(Long).mp3',
    },
  ],
  'Facilities🏢': [
    {
      'label': 'Bonsho Low 1',
      'id': 'bonsho_low1',
      'icon': '🏯',
      'audio': 'sfx/facilities/Bonsho02-1(Low).mp3',
    },
    {
      'label': 'Bonsho Low 2',
      'id': 'bonsho_low2',
      'icon': '🕊️',
      'audio': 'sfx/facilities/Bonsho04-1(Low).mp3',
    },
    {
      'label': 'Chime Announcement 1',
      'id': 'chime_announce1',
      'icon': '🔔',
      'audio': 'sfx/facilities/Chime-Announce02-1.mp3',
    },
    {
      'label': 'Chime Announcement 2',
      'id': 'chime_announce2',
      'icon': '📢',
      'audio': 'sfx/facilities/Chime-Announce07-1.mp3',
    },
    {
      'label': 'Chime Announcement 3',
      'id': 'chime_announce3',
      'icon': '📣',
      'audio': 'sfx/facilities/Chime-Announce07-2.mp3',
    },
    {
      'label': 'Chime Announcement 4',
      'id': 'chime_announce_fast',
      'icon': '⏱️',
      'audio': 'sfx/facilities/Chime-Announce09-1(5-Tone-Fast-Up).mp3',
    },
    {
      'label': 'Crosswalk Signal 1',
      'id': 'crosswalk_signal_loop',
      'icon': '🚦',
      'audio': 'sfx/facilities/Crosswalk-Signal01-1(Loop).mp3',
    },
    {
      'label': 'Crosswalk Signal 2',
      'id': 'crosswalk_signal',
      'icon': '🚧',
      'audio': 'sfx/facilities/Crosswalk-Signal02-1.mp3',
    },
    {
      'label': 'Doorbell Melody',
      'id': 'doorbell_melody',
      'icon': '🏠',
      'audio': 'sfx/facilities/Doorbell-Melody01-1.mp3',
    },
    {
      'label': 'Handheld Transceiver Signal',
      'id': 'transceiver_signal',
      'icon': '📡',
      'audio': 'sfx/facilities/Handheld_Transceiver-Signal01-01(Tx-Call).mp3',
    },
    {
      'label': 'Japanese School Bell 1',
      'id': 'japanese_school_bell_slow',
      'icon': '📚',
      'audio': 'sfx/facilities/Japanese_School_Bell02-01(Slow-Long).mp3',
    },
    {
      'label': 'Japanese School Bell 2',
      'id': 'japanese_school_bell_long',
      'icon': '🕒',
      'audio': 'sfx/facilities/Japanese_School_Bell04-1(Long).mp3',
    },
    {
      'label': 'Japanese School Bell 3',
      'id': 'japanese_school_bell_slow2',
      'icon': '👨‍🏫',
      'audio': 'sfx/facilities/Japanese_School_Bell05-01(Slow-Long).mp3',
    },
    {
      'label': 'Morse Code Fast 1',
      'id': 'morse_code_fast1',
      'icon': '📝',
      'audio': 'sfx/facilities/Morse_Code01-1(Fast).mp3',
    },
    {
      'label': 'Morse Code Fast 2',
      'id': 'morse_code_fast2',
      'icon': '🔍',
      'audio': 'sfx/facilities/Morse_Code02-1(Fast).mp3',
    },
    {
      'label': 'Opening Buzzer 1',
      'id': 'opening_buzzer1',
      'icon': '🚪',
      'audio': 'sfx/facilities/Opening_Buzzer01-1.mp3',
    },
    {
      'label': 'Opening Buzzer 2',
      'id': 'opening_buzzer2',
      'icon': '🔓',
      'audio': 'sfx/facilities/Opening_Buzzer02-1.mp3',
    },
    {
      'label': 'Railroad Crossing Signal',
      'id': 'railroad_crossing_signal',
      'icon': '🚂',
      'audio': 'sfx/facilities/Railroad_Crossing-Signal01-1.mp3',
    },
    {
      'label': 'Time Signal Beep 1',
      'id': 'time_signal_beep_long1',
      'icon': '🕰️',
      'audio': 'sfx/facilities/Time_Signal-Beep01-1(Long).mp3',
    },
    {
      'label': 'Time Signal Beep 2',
      'id': 'time_signal_beep_long2',
      'icon': '📆',
      'audio': 'sfx/facilities/Time_Signal-Beep03-1(Long).mp3',
    },
  ],
  'Vehicles🚑': [
    {
      'label': 'Police Siren Close',
      'id': 'police_siren_close',
      'icon': '🚨',
      'audio': 'sfx/vehicles/Police_Car-Siren03-01(Close).mp3',
    },
    {
      'label': 'Police Siren Slow',
      'id': 'police_siren_slow',
      'icon': '🚨',
      'audio': 'sfx/vehicles/Police_Car-Siren-Fake01-1(Slow).mp3',
    },
    {
      'label': 'Police Siren Far 1',
      'id': 'police_siren_far1',
      'icon': '🚨',
      'audio': 'sfx/vehicles/Police_Car-Siren02-07(Far).mp3',
    },
    {
      'label': 'Police Siren Far 2',
      'id': 'police_siren_far2',
      'icon': '🚨',
      'audio': 'sfx/vehicles/Police_Car-Siren02-08(Far).mp3',
    },
    {
      'label': 'Ambulance Siren 1',
      'id': 'ambulance_siren1',
      'icon': '🚑',
      'audio': 'sfx/vehicles/Ambulance-Siren01-1.mp3',
    },
    {
      'label': 'Ambulance Siren 2',
      'id': 'ambulance_siren2',
      'icon': '🚑',
      'audio': 'sfx/vehicles/Ambulance-Siren01-2.mp3',
    },
    {
      'label': 'Ambulance Siren Close',
      'id': 'ambulance_siren_close',
      'icon': '🚑',
      'audio': 'sfx/vehicles/Ambulance-Siren03-1(Close).mp3',
    },
    {
      'label': 'Ambulance Siren Far',
      'id': 'ambulance_siren_far',
      'icon': '🚑',
      'audio': 'sfx/vehicles/Ambulance-Siren03-3(Far).mp3',
    },
    {
      'label': 'Fire Truck Siren Close',
      'id': 'fire_truck_siren_close',
      'icon': '🚒',
      'audio': 'sfx/vehicles/Fire_Truck-Siren01-01(Close).mp3',
    },
    {
      'label': 'Fire Truck Siren Dry',
      'id': 'fire_truck_siren_dry',
      'icon': '🚒',
      'audio': 'sfx/vehicles/Fire_Truck-Siren01-11(Dry).mp3',
    },
    {
      'label': 'Car Horn 1',
      'id': 'car_horn1',
      'icon': '🚗',
      'audio': 'sfx/vehicles/Car_Horn-Fake01-1.mp3',
    },
    {
      'label': 'Car Horn 2',
      'id': 'car_horn2',
      'icon': '🚗',
      'audio': 'sfx/vehicles/Car_Horn-Fake03-1.mp3',
    },
  ],
  'Home Appliances🛍️': [
    {
      'label': 'Vacuum Cleaner 1',
      'id': 'vacuum_cleaner1',
      'icon': '🧹',
      'audio': 'sfx/appliances/Vacuum_Cleaner01-01(Vacuum).mp3',
    },
    {
      'label': 'Vacuum Cleaner 2',
      'id': 'vacuum_cleaner2',
      'icon': '🧹',
      'audio': 'sfx/appliances/Vacuum_Cleaner02-01(Vacuum).mp3',
    },
    {
      'label': 'Cell Phone Vibration 1',
      'id': 'cell_phone_vibration1',
      'icon': '📱',
      'audio': 'sfx/appliances/Cell_Phone-Vibration02-01(Cushion).mp3',
    },
    {
      'label': 'Cell Phone Vibration 2',
      'id': 'cell_phone_vibration2',
      'icon': '📱',
      'audio': 'sfx/appliances/Cell_Phone-Vibration03-01(Cushion).mp3',
    },
    {
      'label': 'Clock Alarm 1',
      'id': 'clock_alarm_low',
      'icon': '🕰️',
      'audio': 'sfx/appliances/Clock-Alarm01-1(Low-Loop).mp3',
    },
    {
      'label': 'Clock Alarm 2',
      'id': 'clock_alarm_loop',
      'icon': '🕰️',
      'audio': 'sfx/appliances/Clock-Alarm02-1(Loop).mp3',
    },
    {
      'label': 'Clock Alarm 3',
      'id': 'clock_alarm_mid',
      'icon': '🕰️',
      'audio': 'sfx/appliances/Clock-Alarm03-01(Mid-Loop).mp3',
    },
    {
      'label': 'Cuckoo Clock Bell',
      'id': 'cuckoo_clock_bell',
      'icon': '🕰️',
      'audio': 'sfx/appliances/Cuckoo_Clock02-02(Bell-Mid).mp3',
    },
    {
      'label': 'Rotary Phone Ringtone',
      'id': 'rotary_phone_ringtone',
      'icon': '📞',
      'audio': 'sfx/appliances/Rotary_Phone-Ringtone01-1.mp3',
    },
    {
      'label': 'Telephone Music On Hold',
      'id': 'telephone_music_on_hold',
      'icon': '📞',
      'audio': 'sfx/appliances/Telephone-Music_On_Hold01-1(Salut_dAmour).mp3',
    },
    {
      'label': 'Telephone Ringtone',
      'id': 'telephone_ringtone',
      'icon': '📞',
      'audio': 'sfx/appliances/Telephone-Ringtone02-1.mp3',
    },
    {
      'label': 'Telephone Ringback Tone 1',
      'id': 'telephone_ringback1',
      'icon': '📞',
      'audio': 'sfx/appliances/Telephone-Signal_Tone01-1(Ringback).mp3',
    },
    {
      'label': 'Telephone Ringback Tone 2',
      'id': 'telephone_ringback2',
      'icon': '📞',
      'audio': 'sfx/appliances/Telephone-Signal_Tone02-1(Ringback).mp3',
    },
  ],
  'Click 🖱': [
    {
      'label': 'Click1',
      'id': 'click',
      'icon': '🖱️',
      'audio': 'sfx/click/click.mp3',
    },
    {
      'label': 'Click2',
      'id': 'click_2',
      'icon': '🖱️',
      'audio': 'sfx/click/click (1).mp3',
    },
    {
      'label': 'Double Click',
      'id': 'double_click',
      'icon': '🖱️',
      'audio': 'sfx/click/duble_click.mp3',
    },
    {
      'label': 'Camera Shoot',
      'id': 'camera_shoot1',
      'icon': '📸',
      'audio': 'sfx/click/camera_shoot1a.mp3',
    },
    {
      'label': 'Keyboard Typing 1',
      'id': 'type_in1',
      'icon': '🖥️',
      'audio': 'sfx/click/type_in1.mp3',
    },
    {
      'label': 'Keyboard Typing 2',
      'id': 'type_in2',
      'icon': '🖥️',
      'audio': 'sfx/click/type_in2.mp3',
    },
    {
      'label': 'Scanner 1',
      'id': 'scaner1',
      'icon': '🖨️',
      'audio': 'sfx/click/scaner1.mp3',
    },
    {
      'label': 'Scanner 2',
      'id': 'Scanner2',
      'icon': '🖨️',
      'audio': 'sfx/click/scaner2.mp3',
    },
    {
      'label': 'Printer',
      'id': 'new_printer',
      'icon': '🖨️',
      'audio': 'sfx/click/new_printer.mp3',
    },
    {
      'label': 'Fast Printer',
      'id': 'speed_cont_print',
      'icon': '🖨️',
      'audio': 'sfx/click/speed_cont_print.mp3',
    },
  ],
  'Onomatopoeias🗣': [
    {
      'label': 'Button Click Dry',
      'id': 'button_click_dry',
      'icon': '🖱️',
      'audio': 'sfx/onoma/Onoma-Button-Click02-1(Dry).mp3',
    },
    {
      'label': 'Ding Sound',
      'id': 'ding_sound_long',
      'icon': '🔔',
      'audio': 'sfx/onoma/Onoma-Ding04-1(Long).mp3',
    },
    {
      'label': 'Dizzy Sound',
      'id': 'dizzy_sound_fast_short',
      'icon': '🌪️',
      'audio': 'sfx/onoma/Onoma-Dizzy01-1(Fast-Short).mp3',
    },
    {
      'label': 'Fired Up Sound 1',
      'id': 'fired_up_sound1',
      'icon': '🔥',
      'audio': 'sfx/onoma/Onoma-Fired_Up01-1(Long).mp3',
    },
    {
      'label': 'Fired Up Sound 2',
      'id': 'fired_up_sound2',
      'icon': '⚡️',
      'audio': 'sfx/onoma/Onoma-Fired_Up03-1(Long).mp3',
    },
    {
      'label': 'Flash Sound 1',
      'id': 'flash_sound_high_long1',
      'icon': '⚡️',
      'audio': 'sfx/onoma/Onoma-Flash08-1(High-Long).mp3',
    },
    {
      'label': 'Flash Sound 2',
      'id': 'flash_sound_high_long2',
      'icon': '💡',
      'audio': 'sfx/onoma/Onoma-Flash09-1(High-Long).mp3',
    },
    {
      'label': 'Flash Sound 3',
      'id': 'flash_sound_high',
      'icon': '📸',
      'audio': 'sfx/onoma/Onoma-Flash11-1(High).mp3',
    },
    {
      'label': 'Impact Sound Dry 1',
      'id': 'impact_sound_dry1',
      'icon': '💥',
      'audio': 'sfx/onoma/Onoma-Impact02-1(Dry).mp3',
    },
    {
      'label': 'Impact Sound 2',
      'id': 'impact_sound2',
      'icon': '🥊',
      'audio': 'sfx/onoma/Onoma-Impact03-1.mp3',
    },
    {
      'label': 'Impact Sound Dry 3',
      'id': 'impact_sound_dry3',
      'icon': '🔨',
      'audio': 'sfx/onoma/Onoma-Impact14-1(Dry).mp3',
    },
    {
      'label': 'Negative Sound 1',
      'id': 'negative_sound_high_long',
      'icon': '❌',
      'audio': 'sfx/onoma/Onoma-Negative07-1(High-Long).mp3',
    },
    {
      'label': 'Negative Sound 2',
      'id': 'negative_sound_long',
      'icon': '🚫',
      'audio': 'sfx/onoma/Onoma-Negative09-1(Long).mp3',
    },
    {
      'label': 'Negative Sound 3',
      'id': 'negative_sound_fast',
      'icon': '⛔️',
      'audio': 'sfx/onoma/Onoma-Negative14-1(Fast).mp3',
    },
    {
      'label': 'Sparkle Sound',
      'id': 'sparkle_sound_low_short',
      'icon': '✨',
      'audio': 'sfx/onoma/Onoma-Sparkle02-1(Low-Short).mp3',
    },
    {
      'label': 'Surprise Sound',
      'id': 'surprise_sound_low',
      'icon': '😮',
      'audio': 'sfx/onoma/Onoma-Surprise05-1(Low).mp3',
    },
    {
      'label': 'Syakiin Sound Dry',
      'id': 'syakiin_sound_dry',
      'icon': '🎁',
      'audio': 'sfx/onoma/Onoma-Syakiin02-1(Dry).mp3',
    },
  ],
  'Eating 🍙': [
    {
      'label': 'Potato Chips',
      'id': 'potato_chips',
      'icon': '🥔',
      'audio': 'sfx/eating/chips.mp3',
    },
    {
      'label': 'Apple',
      'id': 'apple',
      'icon': '🍎',
      'audio': 'sfx/eating/apple-bite-chew-eat.mp3',
    },
    {
      'label': 'Apple Pear',
      'id': 'apple_pear',
      'icon': '🍎', // リンゴのアイコンを使用
      'audio': 'sfx/eating/VSQSE_0048_applepear_02_eating.mp3',
    },
    {
      'label': 'Carrot',
      'id': 'carrot',
      'icon': '🥕',
      'audio': 'sfx/eating/carrot.mp3',
    },
    {
      'label': 'Corn chips',
      'id': 'corn_chip',
      'icon': '🌽',
      'audio': 'sfx/eating/corn-chip-chewing-03.mp3',
    },
    {
      'label': 'Ice Chewing',
      'id': 'ice_chew',
      'icon': '🧊',
      'audio': 'sfx/eating/ice-chew-1.mp3',
    },
    {
      'label': 'Chip Crunching',
      'id': 'chip_bite',
      'icon': '🍟',
      'audio': 'sfx/eating/eating_chips.mp3',
    },
    {
      'label': 'Cracker 1',
      'id': 'cracker',
      'icon': '🍘',
      'audio': 'sfx/eating/cracker-crunch.mp3',
    },
    {
      'label': 'Cracker 2',
      'id': 'eat_senbei',
      'icon': '🍘',
      'audio': 'sfx/eating/eat_Senbei2.mp3',
    },
    {
      'label': 'Pickle',
      'id': 'pickle',
      'icon': '🥒',
      'audio': 'sfx/eating/eatingapickle.mp3',
    },
    {
      'label': 'Toast',
      'id': 'toast',
      'icon': '🍞',
      'audio': 'sfx/eating/eatingtoast.mp3',
    },
    {
      'label': 'Noodles',
      'id': 'noodles',
      'icon': '🍜',
      'audio': 'sfx/eating/noodles.mp3',
    },
    {
      'label': 'Drink Water 1',
      'id': 'gulp_water1',
      'icon': '💧',
      'audio': 'sfx/eating/gulp_down_water1.mp3',
    },
    {
      'label': 'Drink Water 2',
      'id': 'gulp_water2',
      'icon': '💧',
      'audio': 'sfx/eating/gulp_down_water2.mp3',
    },
    {
      'label': 'Drink Hot Tea 1',
      'id': 'sip_tea1',
      'icon': '🍵',
      'audio': 'sfx/eating/sip_hot_tea1.mp3',
    },
    {
      'label': 'Drink Hot Tea 2',
      'id': 'sip_tea2',
      'icon': '🍵',
      'audio': 'sfx/eating/sip_hot_tea2.mp3',
    },
    {
      'label': 'Pouring Water',
      'id': 'pour_water_cup',
      'icon': '☕️',
      'audio': 'sfx/eating/pour_water_cup.mp3',
    },
    {
      'label': 'Pour Soda 1',
      'id': 'open_soda_can_pour',
      'icon': '🥤',
      'audio': 'sfx/eating/open_soda_can_pour.mp3',
    },
    {
      'label': 'Pour Soda 2',
      'id': 'pour_soda',
      'icon': '🥤',
      'audio': 'sfx/eating/pour_soda.mp3',
    },
    {
      'label': 'Pour Hot Tea',
      'id': 'pour_hot_tea',
      'icon': '🍵',
      'audio': 'sfx/eating/pour_hot_tea.mp3',
    },
    {
      'label': 'Pour Cold Tea',
      'id': 'pour_cold_tea',
      'icon': '🍵',
      'audio': 'sfx/eating/pour_cold_tea.mp3',
    },
    {
      'label': 'Lettuce',
      'id': 'lettuce',
      'icon': '🥗', // レタスのアイコンを使用
      'audio': 'sfx/eating/VSQSE_0247_lettuce.mp3',
    },
    {
      'label': 'Cucumber',
      'id': 'cucumber',
      'icon': '🥒', // キュウリのアイコンを使用
      'audio': 'sfx/eating/VSQSE_0246_cucumber_01.mp3',
    },
    {
      'label': 'Tomato',
      'id': 'cut_tomato',
      'icon': '🍅', // トマトのアイコンを使用
      'audio': 'sfx/eating/VSQSE_0248_tomato_01_cutting.mp3',
    },
  ],
};
